foundation: fusionx
url: https://www.fusionx.net

colors:
  color1: rgba(32, 145, 208, 1)  # 主蓝色
  color2: rgba(75, 47, 169, 1)    # 主紫色
  color3: rgba(255, 105, 0, 1)    # 橙色
  color4: rgba(46, 196, 182, 0.9) # 蓝绿色
  color5: rgba(255, 193, 7, 0.85) # 琥珀色
  color6: rgba(75, 192, 192, 0.85) # 蓝绿色
  color7: rgba(238, 238, 238, 1)  # 浅灰色背景
footer: # 页脚
  links:
    github: https://github.com/openfusionx/FXView
    homepage: https://www.fusionx.net
  logo: https://fxfiles.oss-cn-beijing.aliyuncs.com/openfxview/white_logo.svg
header:
  links:
    github: https://github.com/openfusionx/FXView
  logo: https://fxfiles.oss-cn-beijing.aliyuncs.com/openfxview/yunwanghu.svg
screenshot_width: 1500

featured_items:
  - field: maturity
    options:
      - value: 数智1
        order: 1
        label: FusionX
      - value: 数智2
        order: 2
        label: FusionX
      - value: 数智3
        order: 3
        label: FusionX
      - value: 数智4
        order: 4
        label: FusionX 
      - value: 数智5
        order: 5
        label: FusionX   


grid_items_size: medium

# groups:
#   - name: Open公司
#     categories:
#       - Application应用层
#       - Service服务层
#       - Technology技术层
#       - Infrastructure基础设施层



members_category: 会员